services:
  accounts:
    image: muditkhanna98/accounts:v1.0
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - mudit-network

  loans:
    image: muditkhanna98/loans:v1.0
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - mudit-network

  cards:
    image: muditkhanna98/cards:v1.0
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - mudit-network

networks:
  mudit-network:
    driver: "bridge"
