server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: mu
    password: 12
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import:
      - "application_qa.yml"
      - "application_prod.yml"
  profiles:
    active: "default"

build:
  version: "1.0"

accounts:
  message: "Welcome to accounts related local APIs "
  contactDetails:
    name: "Mudit Khanna - Developer"
    email: "mudit@gmail.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345