services:
  accountsdb:
    image: mysql
    container_name: accountsdb
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: accountsdb
    networks:
      - mudit-network

  loansdb:
    image: mysql
    container_name: loansdb
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: loansdb
    networks:
      - mudit-network

  cardsdb:
    image: mysql
    container_name: cardsdb
    ports:
      - "3308:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cardsdb
    networks:
      - mudit-network

#  config-server:
#    image: muditkhanna98/config-server:v1.0
#    container_name: config-server-ms
#    ports:
#      - "8071:8071"
#    healthcheck:
#      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
#      interval: 10s
#      timeout: 5s
#      retries: 10
#      start_period: 10s
#    deploy:
#      resources:
#        limits:
#          memory: 700m
#    networks:
#      - mudit-network
#
#  accounts:
#    image: muditkhanna98/accounts:v1.0
#    container_name: accounts-ms
#    ports:
#      - "8080:8080"
#    depends_on:
#      config-server:
#        condition: service_healthy
#      accountsdb:
#        condition: service_healthy
#    deploy:
#      resources:
#        limits:
#          memory: 700m
#    networks:
#      - mudit-network
#    environment:
#      SPRING_CONFIG_IMPORT: "configserver:http://config-server:8071"
#      SPRING_PROFILES_ACTIVE: default
#      SPRING_APPLICATION_NAME: accounts
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: root
#      SPRING_DATASOURCE_URL: "jdbc:mysql://accountsdb:3306/accountsdb"
#
#  loans:
#    image: muditkhanna98/loans:v1.0
#    container_name: loans-ms
#    ports:
#      - "8090:8090"
#    depends_on:
#      config-server:
#        condition: service_healthy
#      loansdb:
#        condition: service_healthy
#    deploy:
#      resources:
#        limits:
#          memory: 700m
#    networks:
#      - mudit-network
#    environment:
#      SPRING_CONFIG_IMPORT: "configserver:http://config-server:8071"
#      SPRING_PROFILES_ACTIVE: default
#      SPRING_APPLICATION_NAME: loans
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: root
#      SPRING_DATASOURCE_URL: "jdbc:mysql://loansdb:3306/loansdb"
#
#  cards:
#    image: muditkhanna98/cards:v1.0
#    container_name: cards-ms
#    ports:
#      - "9000:9000"
#    depends_on:
#      config-server:
#        condition: service_healthy
#      cardsdb:
#        condition: service_healthy
#    deploy:
#      resources:
#        limits:
#          memory: 700m
#    networks:
#      - mudit-network
#    environment:
#      SPRING_CONFIG_IMPORT: "configserver:http://config-server:8071"
#      SPRING_PROFILES_ACTIVE: default
#      SPRING_APPLICATION_NAME: cards
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: root
#      SPRING_DATASOURCE_URL: "jdbc:mysql://cardsdb:3306/cardsdb"

networks:
  mudit-network:
    driver: "bridge"
